# Generated by Django 2.2.1 on 2019-06-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.TextField()),
                ('precioCompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('stockActual', models.PositiveSmallIntegerField(default=0)),
                ('unidadDeMedida', models.TextField(default='')),
                ('esInsumo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloManufacturado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoEstiimadoCocina', models.PositiveIntegerField(default=0)),
                ('denominacion', models.TextField(default='')),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RubroArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articulos.Articulo')),
                ('articuloManufacturado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articulos.ArticuloManufacturado')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloManufacturadoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ArticuloManufacturado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articulos.ArticuloManufacturado')),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articulos.Articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubroArticulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articulos.RubroArticulo'),
        ),
    ]
